---
sudo: required

language: python

services:
  - docker

before_install:
- sudo apt-get -qq update

install:
- pip install ansible==2.2.1.0
- pip install ansible-lint
- pip install docker-py
- pip install molecule==1.20.3

script:
- cd ../ && mv ansible-role-terraform kostyrev.terraform && cd kostyrev.terraform
- molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
